name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create config file with API key
        run: |
          mkdir -p shared
          echo 'window.arcgisConfig = { apiKey: "${{ secrets.ARCGIS_API_KEY }}" };' > shared/config.js
          touch .nojekyll
          # Debug: List created files
          ls -la shared/
          cat shared/config.js | sed 's/apiKey: "[^"]*"/apiKey: "REDACTED"/g'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          clean-exclude: |
            .nojekyll
            shared/config.js